<a href="https://colab.research.google.com/github/pradyumn07/ML_Assignment/blob/main/Assignment1_102216048.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1.


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr_rev=np.flip(arr)
print(arr_rev)

[5 4 3 2 1]


In [ ]:
import numpy as np
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
array1=array1.ravel()
print(array1)

[1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1=array1.flatten()
print(array1)

[1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
equal = np.array_equal(arr1, arr2)
print("Arrays are equal:",equal)

Arrays are equal: True


In [ ]:
import numpy as np

x=np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent_value_x=np.bincount(x).argmax()
indices_x = np.where(x == most_frequent_value_x)[0]

print(f"Most frequent value in x: {most_frequent_value_x}")
print(f"Indices of the most frequent value in x: {indices_x}")


Most frequent value in x: 1
Indices of the most frequent value in x: [0 5 7 8 9]


In [ ]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
total_sum = np.sum(gfg)

# ii. Sum of all elements row-wise
row_wise_sum = np.sum(gfg, axis=1)

# iii. Sum of all elements column-wise
column_wise_sum = np.sum(gfg, axis=0)

print("Sum of all elements:", total_sum)
print("Sum of all elements row-wise:", row_wise_sum)
print("Sum of all elements column-wise:", column_wise_sum)


Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


In [ ]:
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# i. Sum of diagonal elements
diagonal_sum = np.trace(n_array)

# ii. Eigenvalues of the matrix
eigenvalues = np.linalg.eigvals(n_array)

# iii. Eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(n_array)

# iv. Inverse of the matrix
inverse_matrix = np.linalg.inv(n_array)

# v. Determinant of the matrix
determinant = np.linalg.det(n_array)

print("Sum of diagonal elements:", diagonal_sum)
print("Eigenvalues of the matrix:", eigenvalues)
print("Eigenvectors of the matrix:\n", eigenvectors)
print("Inverse of the matrix:\n", inverse_matrix)
print("Determinant of the matrix:", determinant)


Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


In [ ]:
import numpy as np
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
result1 = np.dot(p1, q1)
covariance1 = np.cov(p1.flatten(), q1.flatten())

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
result2 = np.dot(p2, q2)
covariance2 = np.cov(p2.flatten(), q2.flatten())
print("i - Matrix multiplication:\n", result1)
print("i - Covariance:\n", covariance1)
print("ii - Matrix multiplication:\n", result2)
print("ii - Covariance:\n", covariance2)


i - Matrix multiplication:
 [[16 19]
 [26 31]]
i - Covariance:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
ii - Matrix multiplication:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
ii - Covariance:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
outer_product = np.outer(x, y)
cartesian_product = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("Inner Product:\n", inner_product)
print("Outer Product:\n", outer_product)
print("Cartesian Product:\n", cartesian_product)


Inner Product:
 [[17 52]
 [13 62]]
Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q.2.

In [ ]:
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])
# i. Element-wise absolute value
absolute_array = np.abs(array)
print("Element-wise absolute value:\n", absolute_array)
flattened_array = array.flatten()

# ii. 25th, 50th and 75th Percentiles
percentile_25_flattened = np.percentile(flattened_array, 25)
percentile_50_flattened = np.percentile(flattened_array, 50)
percentile_75_flattened = np.percentile(flattened_array, 75)

percentile_25_columns = np.percentile(array, 25, axis=0)
percentile_50_columns = np.percentile(array, 50, axis=0)
percentile_75_columns = np.percentile(array, 75, axis=0)

percentile_25_rows = np.percentile(array, 25, axis=1)
percentile_50_rows = np.percentile(array, 50, axis=1)
percentile_75_rows = np.percentile(array, 75, axis=1)

print("\n25th, 50th, 75th Percentiles(Flattened):", percentile_25_flattened, percentile_50_flattened, percentile_75_flattened)
print("25th, 50th, 75th Percentiles(Columns):\n", percentile_25_columns, percentile_50_columns, percentile_75_columns)
print("25th, 50th, 75th Percentiles(Rows):\n", percentile_25_rows, percentile_50_rows, percentile_75_rows)

# iii. Mean, Median and Standard Deviation
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("\nMean, Median, Standard Deviation (Flattened):", mean_flattened, median_flattened, std_flattened)
print("Mean, Median, Standard Deviation (Columns):\n", mean_columns, median_columns, std_columns)
print("Mean, Median, Standard Deviation (Rows):\n", mean_rows, median_rows, std_rows)

Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]

25th, 50th, 75th Percentiles(Flattened): -3.5 -0.5 2.5
25th, 50th, 75th Percentiles(Columns):
 [-2.75 -0.25 -3.75] [-1.5  1.5 -1.5] [-0.25  3.25  0.75]
25th, 50th, 75th Percentiles(Rows):
 [-0.5 -5. ] [ 1. -4.] [2.  0.5]

Mean, Median, Standard Deviation (Flattened): -0.5 -0.5 3.8622100754188224
Mean, Median, Standard Deviation (Columns):
 [-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
Mean, Median, Standard Deviation (Rows):
 [ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]


In [ ]:
import numpy as np
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)
print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


Q.3.
(a)

In [ ]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_elements = np.sort(array)[:4]
largest_elements = np.sort(array)[-5:]
print("array:", array)
print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest_elements)
print("5 largest elements:", largest_elements)

array: [ 10  52  62  16  16  54 453]
Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


(b)


In [ ]:
import numpy as np
array = np.array([1.0,1.2,2.2,2.0,3.0,2.0])
integer_elements = array[array == np.floor(array)]
float_elements = array[array != np.floor(array)]
print("Integer elements only:", integer_elements)
print("Float elements only:", float_elements)

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


Q.4.
(a)

In [6]:
import numpy as np
import cv2
from PIL import Image
import os

def img_to_array(path):
    # Open the image using OpenCV
    img = cv2.imread(path)

    # Check if the image is loaded properly
    if img is None:
        print("Error: Image not found or unable to load.")
        return None

    # Convert the RGB image to grayscale using OpenCV
    grayscale_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Save the grayscale image array to a text file
    np.savetxt("grayscale_image.txt", grayscale_image, fmt='%d')
    print("Grayscale image saved as grayscale_image.txt")

    # Return the original BGR image (OpenCV loads images as BGR)
    return img

# Store the path to the image in a variable
image_path = 'C:\example_image.png'

# Call the function with the image path
img_array = img_to_array(image_path)

# Check if grayscale_image.txt was created and load it
if os.path.exists("grayscale_image.txt"):
    # Load the grayscale image from the text file
    grayscale_image = np.loadtxt("grayscale_image.txt")
    # Display the loaded grayscale image array
    print("Loaded Grayscale Image Array:")
    print(grayscale_image)

# Convert the OpenCV BGR image to RGB format (if you need the RGB channels)
if img_array is not None and img_array.ndim == 3:
    img_array_rgb = cv2.cvtColor(img_array, cv2.COLOR_BGR2RGB)

    # Save each channel of the RGB image separately
    for i in range(3):
        np.savetxt(f"rgb_image_channel_{i}.txt", img_array_rgb[:, :, i], fmt='%d')
    print("RGB image channels saved as rgb_image_channel_0.txt, rgb_image_channel_1.txt, rgb_image_channel_2.txt")

    # Load each channel of the RGB image from their respective text files
    channel_0 = np.loadtxt("rgb_image_channel_0.txt")
    channel_1 = np.loadtxt("rgb_image_channel_1.txt")
    channel_2 = np.loadtxt("rgb_image_channel_2.txt")

    # Stack the channels to reconstruct the RGB image
    rgb_image = np.stack([channel_0, channel_1, channel_2], axis=-1)

    # Display the loaded RGB image array
    print("Loaded RGB Image Array:")
    print(rgb_image)

    # Optionally, you can convert the loaded RGB image to grayscale using numpy
    grayscale_image_np = np.dot(rgb_image[..., :3], [0.2989, 0.5870, 0.1140])

    print("Converted Grayscale Image Array (using numpy):")
    print(grayscale_image_np)

Error: Image not found or unable to load.
